### ISSUE TITLE
main.java  error

### ISSUE THREAD

**Issue by mubarak-coder** [sarafinmahtab/MakeChat-App#1]
giving error when running main.java:
Error: Could not find or load main class application.Main
Caused by: java.lang.ClassNotFoundException: application.Main

**Comment by sarafinmahtab** [comment]
Hi,
Have you checked https://github.com/sarafinmahtab/MakeChat-App#how-to-run it? Did you found the Main.java in both end?

**Comment by mubarak-coder** [comment]
yeah i found the both main.java but when running on eclipse it was giving this error.
I dont know how to handle that. first i upload the database on phpmyadmin through xampp then i tried to run the code.
![problem 1](https://user-images.githubusercontent.com/64554955/80704731-f4ce1f80-8a99-11ea-8b9c-6ea12e2b06f1.PNG)
![problem 2](https://user-images.githubusercontent.com/64554955/80704737-f5ff4c80-8a99-11ea-8ec7-c88a46f19b6e.PNG)

**Comment by sarafinmahtab** [comment]
It seems your JavaFx is not properly configured. Make sure to configure it.
